# Generated by Django 3.2.16 on 2023-03-03 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_auto_20230104_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trash', to='Notes.note')),
            ],
        ),
    ]
