# Generated by Django 3.2.16 on 2023-03-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash', to='Notes.note'),
        ),
    ]
