# Generated by Django 3.2.16 on 2023-03-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_alter_trash_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
