# Generated by Django 3.2.16 on 2023-03-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0010_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='Notes_note_created_049430_idx'),
        ),
    ]
