# Generated by Django 3.2.16 on 2023-03-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0011_auto_20230309_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='note',
            name='Notes_note_created_049430_idx',
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
