# Generated by Django 3.2.16 on 2023-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0012_auto_20230309_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
