# Generated by Django 3.2.16 on 2023-03-17 12:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0017_alter_note_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
